spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: "http://localhost:9098/realms/delivery-microservice"
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                - id: restaurant-service
                  uri: lb:http://RESTAURANT-SERVICE
                  predicates:
                      - Path=/api/v1/restaurants/**
                - id: customer-service
                  uri: lb:http://CUSTOMER-SERVICE
                  predicates:
                      - Path=/api/v1/customers/**
logging:
    level:
        org.springframework.security.oauth2.server.resource: DEBUG

server:
    port: 8222
