eureka:
    instance:
        hostname: localhost
        #preferIpAddress: true
        #hostname: discovery-server
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
            #defaultZone: http://discovery-server:8761/eureka/

spring:
    cloud:
        config:
            override.system-properties: false

management:
    tracing:
        sampling:
            probability: 1.0
