spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/customerdb
        username: root
        password: root
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
    config:
        restaurant-service-url: http://localhost:8222/api/v1/restaurants
        #restaurant-service-url: http://localhost:8050/api/v1/restaurants

server:
    port: 8090


