spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/customerdb
        username: root
        password: root
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    kafka:
        producer:
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.type.mapping: restaurantDTO:com.devshaks.delivery.customer.restaurants.RestaurantDTO

application:
    config:
        restaurant-service-url: http://localhost:8222/api/v1/restaurants
        #restaurant-service-url: http://localhost:8050/api/v1/restaurants

server:
    port: 8090
