spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/orderdb
        username: root
        password: root
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
            database-platform: org.hibernate.dialect.PostgreSQLDialect
    kafka:
        producer:
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.type.mapping: orderConfirmation:com.devshaks.delivery.kafka.OrderConfirmation
        consumer:
            bootstrap-servers: localhost:9092
            group-id: paymentGroup, orderGroup
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: "*" # development only
                spring.json.type.mapping: paymentEvent:com.devshaks.delivery.kafka.PaymentEvent





server:
    port: 8070

application:
    config:
        customer-service-url: http://localhost:8222/api/v1/customers
        restaurant-service-url: http://localhost:8222/api/v1/restaurants
        payment-service-url: http://localhost:8222/api/v1/payments
