FROM openjdk:17-jdk-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY target/restaurant-server-0.0.1-SNAPSHOT.jar /app/restaurant-server.jar

EXPOSE 8050

ENTRYPOINT [ "java", "-jar", "/app/restaurant-server.jar" ]