spring:
    config:
        import: optional:configserver:http://localhost:8888
    application:
        name: customer-service

logging:
    level:
        com.devshaks.delivery.customer.restaurants.RestaurantClient: DEBUG
        org:
            springframework:
                security: DEBUG
