spring:
    profiles:
        active: native # native, dev, prod
    application:
        name: configuration-server
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/configurations # Configuration files location for each microservice

server:
    port: 8888 # Configuration Server port
