FROM openjdk:17-jdk-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY target/configuration-server-0.0.1-SNAPSHOT.jar /app/configuration-server.jar

EXPOSE 8888

ENTRYPOINT [ "java", "-jar", "/app/configuration-server.jar" ]